# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output/"
  device: "gpu"
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 120
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 256, 128]
  save_inference_dir: "./inference"
  eval_mode: "retrieval"

# model architecture
Arch:
  name: "RecModel"
  infer_output_key: "features"
  infer_add_softmax: False
  Backbone:
    name: "ResNet50"
    pretrained: True
  BackboneStopLayer:
    name: "avg_pool"
  Head:
    name: "FC"
    embedding_size: 2048
    class_num: 1501

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.1
    - TripletLoss:
        weight: 1.0
        margin: 0.3
        normalize_feature: false
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Adam
  lr:
    name: Piecewise
    decay_epochs: [30, 60]
    values: [0.00035, 0.000035, 0.0000035]
    warmup_epoch: 10
    warmup_start_lr: 0.0000035
  regularizer:
    name: 'L2'
    coeff: 0.0005

# data loader for train and eval
DataLoader:
  Train:
    dataset:
        name: "VeriWild"
        image_root: "./dataset/market1501"
        cls_label_path: "./dataset/market1501/bounding_box_train.txt"
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: [256, 128]
          - RandFlipImage:
              flip_code: 1
          - Pad:
              padding: 10
          - RandCropImage:
              size: [256, 128]
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
          - RandomErasing:
              EPSILON: 0.5
              sl: 0.02
              sh: 0.4
              r1: 0.3
              mean: [0.4914, 0.4822, 0.4465]
    sampler:
        name: PKSampler
        batch_size: 128
        sample_per_id: 4
        drop_last: True
        shuffle: True
    loader:
        num_workers: 6
        use_shared_memory: True
  Eval:
    Query:
      dataset:
        name: "VeriWild"
        image_root: "./dataset/market1501"
        cls_label_path: "./dataset/market1501/query.txt"
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: [256, 128]
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 6
        use_shared_memory: True

    Gallery:
      dataset:
        name: "VeriWild"
        image_root: "./dataset/market1501"
        cls_label_path: "./dataset/market1501/bounding_box_test.txt"
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: [256, 128]
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
      sampler:
        name: DistributedBatchSampler
        batch_size: 64
        drop_last: False
        shuffle: False
      loader:
        num_workers: 6
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}

