# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output/"
  device: "gpu"
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 26
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 112, 112]
  save_inference_dir: "./inference"
  eval_mode: "adaface"

# model architecture
Arch:
  name: "RecModel"
  infer_output_key: "features"
  infer_add_softmax: False
  Backbone: 
    name: "IR_18"
    pretrained: False
  Head:
    name: "AdaMargin"  
    embedding_size: 512
    class_num: 70722
    m: 0.4
    scale: 32
    h: 0.3333
    t_alpha: 0.01
 
# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Piecewise
    learning_rate: 0.1
    decay_epochs: [12, 20, 24]
    values: [0.1, 0.01, 0.001, 0.0001]
  regularizer:
    name: 'L2'
    coeff: 0.0001

# data loader for train and eval
DataLoader:
  Train:
    dataset:
        name: "AdaFaceDataset"
        root_dir: "/work/dataset/face/"
        label_path: "/work/dataset/face/train_filter_label.txt"
        low_res_augmentation_prob: 0.2
        crop_augmentation_prob: 0.2
        photometric_augmentation_prob: 0.2
        transform:
          - RandomHorizontalFlip:
          - ToTensor:
          - Normalize:
              mean: [0.5, 0.5, 0.5]
              std: [0.5, 0.5, 0.5]

    sampler:
        name: DistributedBatchSampler
        batch_size: 256
        drop_last: False
        shuffle: True
    loader:
        num_workers: 6
        use_shared_memory: True
  Eval:
    dataset:
      name: FiveValidationDataset
      val_data_path: /work/dataset/face/faces_emore
      concat_mem_file_name: /work/dataset/face/faces_emore/concat_validation_memfile
    sampler:
        name: DistributedBatchSampler
        batch_size: 256
        drop_last: False
        shuffle: True
    loader:
        num_workers: 6
        use_shared_memory: True